### ISSUE TITLE
Failed to read from defunct connection IPv4Address 

### ISSUE THREAD

**Issue by swanandbagve** [neo4j-labs/llm-graph-builder#313]
2024-05-15 11:14:56,773 - graph_documents = 124

I get this error message on console when trying to ingest file
raise ServiceUnavailable(message) from error
neo4j.exceptions.ServiceUnavailable: Failed to read from defunct connection IPv4Address(('xxx.westeurope.azurecontainer.io', 7687)) (ResolvedIPv4Address(('xx.xx.xx.xxx', 7687)))
This creates graph but shows status of the file as Failed and upload progress also shows as NA from success

**Comment by jexp** [comment]
Hmm, is that xxx.westeurope.azurecontainer.io your database location or the location where you're running docker?
Any more details on your setup or deployment? And any more log details?

**Comment by swanandbagve** [comment]
Hi @jexp 
024-05-16 09:16:07,193 - update embedding and vector index for chunks
2024-05-16 09:17:18,006 - Get graph document list from models
2024-05-16 09:17:18,006 - allowedNodes: ['Financial Metrics', 'Business Segments', 'Key Performance Indicators', 'Geographic Regions', 'Product Lines', 'Market Trends and Outlook'], allowedRelationship: ['has a', 'is a', 'is part of', 'is in', 'is about', 'is located in', 'is related to', 'is a type of', 'is a subset of', 'is a part of', 'is a member of', 'is a category of', 'is a segment of', 'is a division of', 'is a unit of', 'is a region of', 'is a sector of', 'is a type of', 'is a kind of', 'is a class of', 'is a category of', 'is a subset of', 'is a part of', 'is a member of', 'is a segment of', 'is a division of', 'is a unit of', 'is a region of', 'is a sector of', 'is a type of', 'is a kind of', 'is a class of', 'is a category of', 'is a subset of', 'is a part of', 'is a member of', 'is a segment of', 'is a division of', 'is a unit of', 'is a region of', 'is a sector of', 'is a type of', 'is a kind of', 'is a class of', 'is a category of', 'is a subset of', 'is a part of', 'is a member of', 'is a segment of', 'is a division of', 'is a unit of', 'is a region of', 'is a sector of', 'is a type of', 'is a kind of', 'is a class of', 'is a category of', 'is a subset of', 'is a part of', 'is a member of', 'is a segment of', 'is a division of', 'is a unit of', 'is a region of', 'is a sector of', 'is a type of', 'is a kind of', 'is a class of', 'is a category of', 'is a subset of', 'is a part of', 'is a member of', 'is a segment of', 'is a division of', 'is a unit of', 'is a region of', 'is a sector of', 'is a type of', 'is a kind of', 'is a class of', 'is a category of', 'is a subset of', 'is a part of', 'is a member of', 'is a segment of', 'is a division of', 'is a unit of', 'is a region of', 'is a sector of', 'is a type of', 'is a kind of', 'is a class of', 'is a category of', 'is a subset of', 'is a part of', 'is a member of', 'is a segment of', 'is a division of', 'is a unit of', 'is a region of', 'is a sector of', 'is a type of', 'is a kind of']
2024-05-16 09:17:18,006 - Combining 3 chunks before sending request to LLM
2024-05-16 09:21:39,615 - graph_documents = 124
2024-05-16 09:21:58,616 - Failed to read from defunct connection IPv4Address(('xxx.westeurope.azurecontainer.io', 7687)) (ResolvedIPv4Address(('xx.xx.xxx.xxx', 7687)))
2024-05-16 09:21:58,835 - {"message": " Failed To Process File:HSBC-1q-2024-earnings-release.pdf or LLM Unable To Parse Content", "error_message": "Failed to read from defunct connection IPv4Address(('xxx.westeurope.azurecontainer.io', 7687)) (ResolvedIPv4Address(('xx.xx.xxx.xxx', 7687)))", "file_name": "HSBC-1q-2024-earnings-release.pdf", "status": "Failed", "url": "bolt+ssc://xxx.westeurope.azurecontainer.io:7687", "failed_count": 1, "source_type": "local file"}
2024-05-16 09:21:58,835 - File Failed in extraction: {'message': ' Failed To Process File:HSBC-1q-2024-earnings-release.pdf or LLM Unable To Parse Content', 'error_message': "Failed to read from defunct connection IPv4Address(('xxx.westeurope.azurecontainer.io', 7687)) (ResolvedIPv4Address(('xx.xx.xxx.xxx', 7687)))", 'file_name': 'HSBC-1q-2024-earnings-release.pdf', 'status': 'Failed', 'url': 'bolt+ssc://xxx.westeurope.azurecontainer.io:7687', 'failed_count': 1, 'source_type': 'local file'}
Traceback (most recent call last):
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\envDemo\Lib\site-packages\neo4j\_sync\io\_common.py", line 51, in _buffer_one_chunk
    receive_into_buffer(self._socket, self._buffer, 2)
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\envDemo\Lib\site-packages\neo4j\_sync\io\_common.py", line 328, in receive_into_buffer
    raise OSError("No data")
OSError: No data
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\score.py", line 154, in extract_knowledge_graph_from_file
    result = await asyncio.to_thread(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\src\main.py", line 173, in extract_graph_from_file_local_file
    return processing_source(graph, model, file_name, pages, allowedNodes, allowedRelationship, merged_file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\src\main.py", line 270, in processing_source
    save_graphDocuments_in_neo4j(graph, graph_documents)
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\src\shared\common_fn.py", line 88, in save_graphDocuments_in_neo4j
    graph.add_graph_documents(graph_document_list)
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\envDemo\Lib\site-packages\langchain_community\graphs\neo4j_graph.py", line 543, in add_graph_documents
    self.query(
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\envDemo\Lib\site-packages\langchain_community\graphs\neo4j_graph.py", line 391, in query
    data = session.run(Query(text=query, timeout=self.timeout), params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\envDemo\Lib\site-packages\neo4j\_sync\work\session.py", line 313, in run
    self._auto_result._run(
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\envDemo\Lib\site-packages\neo4j\_sync\work\result.py", line 181, in _run
    self._attach()
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\envDemo\Lib\site-packages\neo4j\_sync\work\result.py", line 301, in _attach
    self._connection.fetch_message()
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\envDemo\Lib\site-packages\neo4j\_sync\io\_common.py", line 178, in inner
    func(*args, **kwargs)
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\envDemo\Lib\site-packages\neo4j\_sync\io\_bolt.py", line 846, in fetch_message
    tag, fields = self.inbox.pop(
                  ^^^^^^^^^^^^^^^
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\envDemo\Lib\site-packages\neo4j\_sync\io\_common.py", line 72, in pop
    self._buffer_one_chunk()
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\envDemo\Lib\site-packages\neo4j\_sync\io\_common.py", line 68, in _buffer_one_chunk
    Util.callback(self.on_error, error)
  File "C:\neo4j\llm-graph-builder-DEV\llm-graph-builder-DEV\backend\envDemo\Lib\site-packages\neo4j\_async_compat\util.py", line 118, in callback

**Comment by swanandbagve** [comment]
Hi @jexp 
neo4j is installed on ACI (azure container instance) in our azure cloud and I am using the code to spin up the application from an Azure VM.
I also tried to do this locally with a local neo4j install but its not working with the code and the app refuses to connect to neo4j instance despite trying all connection schemes

**Comment by jexp** [comment]
Can you connect from the azure vm eg using cypher shell. Could be some firewall. 
and Im not sure on windows if you have to configure something in docker network to allow connections to the outside?

**Comment by swanandbagve** [comment]
Hi @jexp , the connectivity from application hosted on azure VM is working and nodes are also getting created in graph along with relationships before this error occurs. However have selected allowed Nodes and relationships but its not detecting any of these and adding to the graph and just adding the default chunks driven relationships namely FIRST_CHUNK, NEXT_CHUNK, PART_OF. Also the entities are chunk, document and session only and no named entities I am trying to provide . And then i get the error pasted earlier above. From reading the error message trail it looks like some timeout due to some setting in code ? can u check if this runs at your end please and what is connection URL and scheme format u use? i also tried to do this on local neo4j instance but no luck with connectivity. So container instance atleast partially works before hitting timeout but the local one i am not able to establish connectivity at all. can u confirm if there is some timeout in neo4j ?

**Comment by jexp** [comment]
Would you be able to record a short screencast and share that?

Yes there is a timeout setting in the code but it's pretty long (30 mins or so). 

@kartikpersistent ?

**Comment by jexp** [comment]
Neo4j connection itself also has a connection timeout by default I think 30seconds

**Comment by swanandbagve** [comment]
Hi @jexp , any idea where to change this connection timeout ? https://neo4j.com/docs/operations-manual/current/database-internals/transaction-management/ seems to suggest by default there is no timeout from neo4j

**Comment by swanandbagve** [comment]
I guess @jexp i need to change it in neo4j.conf and this can't be changed in the code ?

**Comment by jexp** [comment]
Yeah actually it's a driver config that you need to pass to Neo4jGraph - but it should never take 30s+ in real circumstances.
