### ISSUE TITLE
Error: [vite]: Rollup failed to resolve import "@segment/analytics-next" from "/app/node_modules/@neo4j-nvl/base/dist/base.mjs".

### ISSUE THREAD

**Issue by shutter-cp** [neo4j-labs/llm-graph-builder#672]
```log
 => ERROR [frontend build 7/7] RUN BACKEND_API_URL=http://localhost:8000     REACT_APP_SOURCES=local,youtube,wiki,s3     LLM_MODELS=diffbot,openai-gpt-  7.4s
------
 > [frontend build 7/7] RUN BACKEND_API_URL=http://localhost:8000     REACT_APP_SOURCES=local,youtube,wiki,s3     LLM_MODELS=diffbot,openai-gpt-3.5,openai-gpt-4o     GOOGLE_CLIENT_ID=""     BLOOM_URL=https://workspace-preview.neo4j.io/workspace/explore?connectURL={CONNECT_URL}&search=Show+me+a+graph&featureGenAISuggestions=true&featureGenAISuggestionsInternal=true     TIME_PER_CHUNK=4     CHUNK_SIZE=5242880     ENV=DEV     LARGE_FILE_SIZE=5242880     CHAT_MODES=""     yarn run build:
0.108 yarn run v1.22.22
0.120 $ tsc && vite build
3.426 vite v4.5.3 building for production...
3.440 transforming...
3.783 
3.783 warn - The safelist pattern `/^(hover:)?n-text-(palette|dark|light|primary|danger|warning|success|blueberry|mint|neutral)-/` doesn't match any Tailwind CSS classes.
3.783 warn - Fix this pattern or remove it from your `safelist` configuration.
3.783 warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes
3.783 
3.783 warn - The safelist pattern `/^(hover:)?n-bg-(palette|dark|light|primary|danger|warning|success|blueberry|mint|neutral)-/` doesn't match any Tailwind CSS classes.
3.783 warn - Fix this pattern or remove it from your `safelist` configuration.
3.783 warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes
3.784 
3.784 warn - The safelist pattern `/^(active:)?n-bg-(palette|dark|light|primary|danger|warning|success|blueberry|mint|neutral)-/` doesn't match any Tailwind CSS classes.
3.784 warn - Fix this pattern or remove it from your `safelist` configuration.
3.784 warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes
3.784 
3.784 warn - The safelist pattern `/^(hover:)?n-border-(palette|dark|light|primary|danger|warning|success|blueberry|mint|neutral)-/` doesn't match any Tailwind CSS classes.
3.784 warn - Fix this pattern or remove it from your `safelist` configuration.
3.784 warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes
7.298 ✓ 2621 modules transformed.
7.298 ✓ built in 3.87s
7.298 [vite]: Rollup failed to resolve import "@segment/analytics-next" from "/app/node_modules/@neo4j-nvl/base/dist/base.mjs".
7.298 This is most likely unintended because it can break your application at runtime.
7.298 If you do want to externalize this module explicitly add it to
7.298 `build.rollupOptions.external`
7.303 error during build:
7.303 Error: [vite]: Rollup failed to resolve import "@segment/analytics-next" from "/app/node_modules/@neo4j-nvl/base/dist/base.mjs".
7.303 This is most likely unintended because it can break your application at runtime.
7.303 If you do want to externalize this module explicitly add it to
7.303 `build.rollupOptions.external`
7.303     at viteWarn (file:///app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:48216:27)
7.303     at onwarn (file:///app/node_modules/@vitejs/plugin-react/dist/index.mjs:266:9)
7.303     at onRollupWarning (file:///app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:48245:9)
7.303     at onwarn (file:///app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:47976:13)
7.303     at file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
7.303     at Object.logger [as onLog] (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
7.303     at ModuleLoader.handleInvalidResolvedId (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
7.303     at file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
7.330 error Command failed with exit code 1.
7.330 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c BACKEND_API_URL=$BACKEND_API_URL     REACT_APP_SOURCES=$REACT_APP_SOURCES     LLM_MODELS=$LLM_MODELS     GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID     BLOOM_URL=$BLOOM_URL     TIME_PER_CHUNK=$TIME_PER_CHUNK     CHUNK_SIZE=$CHUNK_SIZE     ENV=$ENV     LARGE_FILE_SIZE=${LARGE_FILE_SIZE}     CHAT_MODES=$CHAT_MODES     yarn run build" did not complete successfully: exit code: 1
```

**Comment by kartikpersistent** [comment]
https://github.com/neo4j-labs/llm-graph-builder/issues/669
