### ISSUE TITLE
Does the Graph builder support GPU?

### ISSUE THREAD

**Issue by edenbuaa** [neo4j-labs/llm-graph-builder#708]
How to use GPU to load model?

**Comment by karanchellani** [comment]
@edenbuaa, most of the model providers that we use do provide GPU support, however, for embedding generation we don't use GPU's. Let me know if you have any further queries.

**Comment by edenbuaa** [comment]
@karanchellani got it, thanks.

Another question is I always got error when process file to generate graph:

```
Traceback (most recent call last):
backend     |   File "/code/score.py", line 163, in extract_knowledge_graph_from_file
backend     |     result = await asyncio.to_thread(
backend     |   File "/usr/local/lib/python3.10/asyncio/threads.py", line 25, in to_thread
backend     |     return await loop.run_in_executor(None, func_call)
backend     |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
backend     |     result = self.fn(*self.args, **self.kwargs)
backend     |   File "/code/src/main.py", line 197, in extract_graph_from_file_local_file
backend     |     return processing_source(uri, userName, password, database, model, file_name, pages, allowedNodes, allowedRelationship, True, merged_file_path)
backend     |   File "/code/src/main.py", line 315, in processing_source
backend     |     node_count,rel_count = processing_chunks(selected_chunks,graph,uri, userName, password, database,file_name,model,allowedNodes,allowedRelationship,node_count, rel_count)
backend     |   File "/code/src/main.py", line 382, in processing_chunks
backend     |     graph_documents =  get_graph_from_llm(model, chunkId_chunkDoc_list, allowedNodes, allowedRelationship)
backend     |   File "/code/src/llm.py", line 194, in get_graph_from_llm
backend     |     graph_document_list = get_graph_document_list(
backend     |   File "/code/src/llm.py", line 174, in get_graph_document_list
backend     |     graph_document = future.result()
backend     |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
backend     |     return self.__get_result()
backend     |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
backend     |     raise self._exception
backend     |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
backend     |     result = self.fn(*self.args, **self.kwargs)
backend     |   File "/usr/local/lib/python3.10/site-packages/langchain_experimental/graph_transformers/llm.py", line 782, in convert_to_graph_documents
backend     |     return [self.process_response(document, config) for document in documents]
backend     |   File "/usr/local/lib/python3.10/site-packages/langchain_experimental/graph_transformers/llm.py", line 782, in <listcomp>
backend     |     return [self.process_response(document, config) for document in documents]
backend     |   File "/usr/local/lib/python3.10/site-packages/langchain_experimental/graph_transformers/llm.py", line 734, in process_response
backend     |     nodes_set.add((rel["head"], rel["head_type"]))
backend     | KeyError: 'head'
```

Any suggestion?

**Comment by aashipandya** [comment]
Are you using latest version of langchain_experimental?

**Comment by edenbuaa** [comment]
@aashipandya yes, I use the `DEV `branch, and the `langchain-experimental` version is `0.0.64`
