### ISSUE TITLE
Connection to Neo4j DB seems to expire after an amount of time

### ISSUE THREAD

**Issue by mystvearn** [neo4j-labs/llm-graph-builder#764]
I'm using this amazing project to extract and model information from biomedical textbook. Since it's a large textbook I had to break it into pages. The Generate Graph function is executed smoothly for a period of time then the following error occurs:

```
backend   | 2024-09-25 14:21:50,690 -  SSE Client disconnected
backend   | [2024-09-25 14:22:01 +0000] [12] [ERROR] Exception in ASGI application
backend   | Traceback (most recent call last):
backend   |   File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 284, in __call__
backend   |     await wrap(partial(self.listen_for_disconnect, receive))
backend   |   File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 273, in wrap
backend   |     await func()
backend   |   File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 223, in listen_for_disconnect
backend   |     message = await receive()
backend   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 553, in receive
backend   |     await self.message_event.wait()
backend   |   File "/usr/local/lib/python3.10/asyncio/locks.py", line 214, in wait
backend   |     await fut
backend   | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f2bec518ee0
backend   |
backend   | During handling of the above exception, another exception occurred:
backend   |
backend   |   + Exception Group Traceback (most recent call last):
backend   |   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
backend   |   |     result = await app(  # type: ignore[func-returns-value]
backend   |   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
backend   |   |     return await self.app(scope, receive, send)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
backend   |   |     await super().__call__(scope, receive, send)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
backend   |   |     await self.middleware_stack(scope, receive, send)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
backend   |   |     raise exc
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
backend   |   |     await self.app(scope, receive, _send)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 85, in __call__
backend   |   |     await self.app(scope, receive, send_wrapper)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
backend   |   |     await self.simple_response(scope, receive, send, request_headers=headers)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 148, in simple_response
backend   |   |     await self.app(scope, receive, send)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
backend   |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
backend   |   |     raise exc
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend   |   |     await app(scope, receive, sender)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
backend   |   |     await self.middleware_stack(scope, receive, send)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
backend   |   |     await route.handle(scope, receive, send)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
backend   |   |     await self.app(scope, receive, send)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
backend   |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
backend   |   |     raise exc
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
backend   |   |     await app(scope, receive, sender)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
backend   |   |     await response(scope, receive, send)
backend   |   |   File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 270, in __call__
backend   |   |     async with anyio.create_task_group() as task_group:
backend   |   |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
backend   |   |     raise BaseExceptionGroup(
backend   |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
backend   |   +-+---------------- 1 ----------------
backend   |     | Traceback (most recent call last):
backend   |     |   File "/usr/local/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 920, in acquire
backend   |     |     address = self._select_address(
backend   |     |   File "/usr/local/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 881, in _select_address
backend   |     |     raise ReadServiceUnavailable(
backend   |     | neo4j.exceptions.ReadServiceUnavailable: No read service currently available
backend   |     |
backend   |     | The above exception was the direct cause of the following exception:
backend   |     |
backend   |     | Traceback (most recent call last):
backend   |     |   File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 273, in wrap
backend   |     |     await func()
backend   |     |   File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 253, in stream_response
backend   |     |     async for data in self.body_iterator:
backend   |     |   File "/code/score.py", line 460, in generate
backend   |     |     graph = create_graph_database_connection(uri, userName, decoded_password, database)
backend   |     |   File "/code/src/shared/common_fn.py", line 73, in create_graph_database_connection
backend   |     |     graph = Neo4jGraph(url=uri, database=database, username=userName, password=password, refresh_schema=False, sanitize=True)
backend   |     |   File "/usr/local/lib/python3.10/site-packages/langchain_community/graphs/neo4j_graph.py", line 379, in __init__
backend   |     |     self._driver.verify_connectivity()
backend   |     |   File "/usr/local/lib/python3.10/site-packages/neo4j/_sync/driver.py", line 1067, in verify_connectivity
backend   |     |     self._get_server_info(session_config)
backend   |     |   File "/usr/local/lib/python3.10/site-packages/neo4j/_sync/driver.py", line 1281, in _get_server_info
backend   |     |     return session._get_server_info()
backend   |     |   File "/usr/local/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 172, in _get_server_info
backend   |     |     self._connect(READ_ACCESS, liveness_check_timeout=0)
backend   |     |   File "/usr/local/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 130, in _connect
backend   |     |     super()._connect(
backend   |     |   File "/usr/local/lib/python3.10/site-packages/neo4j/_sync/work/workspace.py", line 182, in _connect
backend   |     |     self._connection = self._pool.acquire(**acquire_kwargs_)
backend   |     |   File "/usr/local/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 924, in acquire
backend   |     |     raise SessionExpired("Failed to obtain connection towards '%s' server." % access_mode) from err
backend   |     | neo4j.exceptions.SessionExpired: Failed to obtain connection towards 'READ' server.
```

If I refresh the page then everything is back to normal. But I have to do it from time to time which is very frustrating.

**Comment by kartikpersistent** [comment]
@praveshkumar1988

**Comment by simons2wyn** [comment]
I met the same bug and tried a lot, but can't fix it up...
