### ISSUE TITLE
SSL verification failed when running the backend

### ISSUE THREAD

**Issue by Ms9208908566** [neo4j-labs/llm-graph-builder#817]
(envName) PS C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend> uvicorn score:app --reload
INFO:     Will watch for changes in these directories: ['C:\\Users\\XJ768PU\\Downloads\\llm-graph-builder-main (1)\\llm-graph-builder-main\\backend']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [33884] using WatchFiles
2024-10-22 14:10:20,394 - USER_AGENT environment variable not set, consider setting it to identify your requests.
2024-10-22 14:10:24,804 - Use pytorch device_name: cpu
2024-10-22 14:10:24,805 - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\urllib3\connection.py", line 738, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\urllib3\connection.py", line 917, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1104, in _create
    self.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn-lfs.hf.co', port=443): Max retries exceeded with url: /sentence-transformers/all-MiniLM-L6-v2/53aa51172d142c89d9012cce15ae4d6cc0ca6895895114379cacb4fab128d9db?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1729843672&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyOTg0MzY3Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5oZi5jby9zZW50ZW5jZS10cmFuc2Zvcm1lcnMvYWxsLU1pbmlMTS1MNi12Mi81M2FhNTExNzJkMTQyYzg5ZDkwMTJjY2UxNWFlNGQ2Y2MwY2E2ODk1ODk1MTE0Mzc5Y2FjYjRmYWIxMjhkOWRiP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=SCUVRoD~oIyLAcySqXiIj5K8APkzzA8I~iaPlwuy61VpnX82lppl1FWMKDSKMamd0cUybRb4gYQd1lmAogptAHl1UbID0t~jJy31El3s4CwirOYD3GnWSUdXcNk4BZYNgwUXujlaUzTSa8FVkknCfE8t5jZqSQMHBndrPUR8rINZ~UZjGKofdGnSAVGIdwSE1FaN~AEVO9EJME05xeSjYP5WiZDlMjxdegescBx2LgtvdsJLLilmcZvLm98JgrvKO9lTRozrJs0OAGKf2KMFI~-OgwIV2qHv~Pp6PY1ytwiASs4LfP55Qf30NKeFYeGeRpJHxbZucYBO1IMdPxZlCQ__&Key-Pair-Id=K3RPWS32NSSJCE (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\uvicorn\_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\uvicorn\config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\score.py", line 5, in <module> 
    from src.QA_integration_new import *
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\src\QA_integration_new.py", line 39, in <module>
    EMBEDDING_FUNCTION , _ = load_embedding_model(EMBEDDING_MODEL)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\src\shared\common_fn.py", line 
89, in load_embedding_model
    embeddings = SentenceTransformerEmbeddings(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\langchain_core\_api\deprecation.py", line 215, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\langchain_community\embeddings\huggingface.py", line 92, in __init__
    self.client = sentence_transformers.SentenceTransformer(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 287, in __init__
    modules = self._load_sbert_model(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 1487, in _load_sbert_model
    module = Transformer(model_name_or_path, cache_dir=cache_folder, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\sentence_transformers\models\Transformer.py", line 54, in __init__
    self._load_model(model_name_or_path, config, cache_dir, **model_args)
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\sentence_transformers\models\Transformer.py", line 85, in _load_model
    self.auto_model = AutoModel.from_pretrained(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\transformers\modeling_utils.py", line 3428, in from_pretrained
    resolved_archive_file = cached_file(pretrained_model_name_or_path, filename, **cached_file_kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\transformers\utils\hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\huggingface_hub\file_download.py", line 1011, in _hf_hub_download_to_cache_dir
    _download_to_tmp_and_move(
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\huggingface_hub\file_download.py", line 1545, in _download_to_tmp_and_move
    http_get(
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\huggingface_hub\file_download.py", line 368, in http_get
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\huggingface_hub\file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\huggingface_hub\utils\_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\requests\adapters.py", line 698, in send
ngface_hub\utils\_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\requests\adapters.py", line 698, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\requests\adapters.py", line 698, in send
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\requests\adapters.py", line 698, in send
  File "C:\Users\XJ768PU\Downloads\llm-graph-builder-main (1)\llm-graph-builder-main\backend\envName\Lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs.hf.co', port=443): Max retries exceeded with url: /sentence-transformers/all-MiniLM-L6-v2/53aa51172d142c89d9012cce15ae4d6cc0ca6895895114379cacb4fab128d9db?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1729843672&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyOTg0MzY3Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5oZi5jby9zZW50ZW5jZS10cmFuc2Zvcm1lcnMvYWxsLU1pbmlMTS1MNi12Mi81M2FhNTExNzJkMTQyYzg5ZDkwMTJjY2UxNWFlNGQ2Y2MwY2E2ODk1ODk1MTE0Mzc5Y2FjYjRmYWIxMjhkOWRiP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=SCUVRoD~oIyLAcySqXiIj5K8APkzzA8I~iaPlwuy61VpnX82lppl1FWMKDSKMamd0cUybRb4gYQd1lmAogptAHl1UbID0t~jJy31El3s4CwirOYD3GnWSUdXcNk4BZYNgwUXujlaUzTSa8FVkknCfE8t5jZqSQMHBndrPUR8rINZ~UZjGKofdGnSAVGIdwSE1FaN~AEVO9EJME05xeSjYP5WiZDlMjxdegescBx2LgtvdsJLLilmcZvLm98JgrvKO9lTRozrJs0OAGKf2KMFI~-OgwIV2qHv~Pp6PY1ytwiASs4LfP55Qf30NKeFYeGeRpJHxbZucYBO1IMdPxZlCQ__&Key-Pair-Id=K3RPWS32NSSJCE (Caused by SSLError(SSLent-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1729843672&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyOTg0MzY3Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5oZi5jby9zZW50ZW5jZS10cmFuc2Zvcm1lcnMvYWxsLU1pbmlMTS1MNi12Mi81M2FhNTExNzJkMTQyYzg5ZDkwMTJjY2UxNWFlNGQ2Y2MwY2E2ODk1ODk1MTE0Mzc5Y2FjYjRmYWIxMjhkOWRiP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=SCUVRoD~oIyLAcySqXiIj5K8APkzzA8I~iaPlwuy61VpnX82lppl1FWMKDSKMamd0cUybRb4gYQd1lmAogptAHl1UbID0t~jJy31El3s4CwirOYD3GnWSUdXcNk4BZYNgwUXujlaUzTSa8FVkknCfE8t5jZqSQMHBndrPUR8rINZ~UZjGKofdGnSAVGIdwSE1FaN~AEVO9EJME05xeSjYP5WiZDlMjxdegescBx2LgtvdsJLLilmcZvLm98JgrvKO9lTRozrJs0OAGKent-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1729843672&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyOTg0MzY3Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5oZi5jby9zZW50ZW5jZS10cmFuc2Zvcm1lcnMvYWxsLU1pbmlMTS1MNi12Mi81M2FhNTExNzJkMTQyYzg5ZDkwMTJjY2UxNWFlNGQ2Y2MwY2E2ODk1ODk1MTE0Mzc5Y2FjYjRmYWIxMjhkOWRiP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=SCUVRoD~oIyLAcySqXiIj5K8APkzzA8I~iaPlwuy61VpnX82lppl1FWMKDSKMamd0cUybRb4gYQd1lmAogptAHl1UbID0t~jJy31El3s4CwirOYD3GnWSUdXcNk4BZYNgwUXujlaUzTSa8FVkknent-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1729843672&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyOTg0MzY3Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5oZi5jby9zZW50ZW5jZS10cmFuc2Zvcm1lcnMvYWxsLU1pbmlMTS1MNi12Mi81M2FhNTExNzJkMTQyYzg5ZDkwMTJjY2UxNWFlNGQ2Y2MwY2E2ODk1ODk1MTE0Mzc5Y2FjYjRmYWIxMjhkOWRiP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=SCUVRoD~oIyLAcySqXiIj5Kent-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1729843672&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyOTg0MzY3Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5oZi5jby9zZW50ZW5jZS10cmFuc2Zvcm1lcnMvYWxsLU1pbmlMTS1MNi12Mi81M2FhNTExNzJkMTQyYzg5ZDkwMTJjY2UxNWFlNGQ2Y2ent-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1729843672&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyOTg0MzY3Mn19LCJSZXNvdXJjZSI6Iment-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=17298436ent-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1729843672&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyOTg0MzY3Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5oZi5jby9zZW50ZW5jZS10cmFuc2Zvcm1lcnMvYWxsLU1pbmlMTS1MNi12Mi81M2FhNTExNzJkMTQyYzg5ZDkwMTJjY2UxNWFlNGQ2Y2MwY2E2ODk1ODk1MTE0Mzc5Y2FjYjRmYWIxMjhkOWRiP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=SCUVRoD~oIyLAcySqXiIj5K72&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyOTg0MzY3Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5oZi5jby9zZW50ZW5jZS10cmFuc2Zvcm1lcnMvYWxsLU1pbmlMTS1MNi12Mi81M2FhNTExNzJkMTQyYzg5ZDkwMTJjY2UxNWFlNGQ2Y2MwY2E2ODk1ODk1MTE0Mzc5Y2FjYjRmYWIxMjhkOWRiP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=SCUVRoD~oIyLAcySqXiIj5K8APkzzA8I~iaPlwuy61VpnX82lppl1FWMKDSKMamd0cUybRb4gYQd1lmAogptAHl1UbID0t~jJy31El3s4CwirOYD3GnWSUdXcNk4BZYNgwUXujlaUzTSa8FVkknCfE8t5jZqSQMHBndrPUR8rINZ~UZjGKofdGnSAVGIdwSE1FaN~AEVO9EJME05xeSjYP5WiZDlMjxdegescBx2LgtvdsJLLilmcZvLm98JgrvKO9lTRozrJs0OAGKf2KMFI~-OgwIV2qHv~Pp6PY1ytwiASs4LfP55Qf30NKeFYeGeRpJHxbZucYBO1IMdPxZlCQ__&Key-Pair-Id=K3RPWS32NSSJCE (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))"), '(Request ID: 08c92b4b-90eb-4737-b1c0-e8692a6d6557)')

**Comment by praveshkumar1988** [comment]
Hi @Ms9208908566 You need to update local SSL ca-certificate file. Try this link to fix the issue https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests
