### ISSUE TITLE
Getting 404 when trying to process files with Ollama-llama3

### ISSUE THREAD

**Issue by Anesbett1** [neo4j-labs/llm-graph-builder#883]
I am tyring to process a Wikipedia article with Ollama-llama3. I believe I have the project setup correctly but when processing a file when I click "Generate Graph" I am getting a failed error message. Is llama3 working with this setup? Here are the logs I'm seeing on the backend: 

`INFO:     127.0.0.1:57866 - "GET /update_extract_status/The_Lord_of_the_Rings?url=bolt://localhost:7687&userName=****&password=****&database=neo4j HTTP/1.1" 200 OK
[ERROR]{'message': 'Failed To Process File:The_Lord_of_the_Rings or LLM Unable To Parse Content ', 
'error_message': 'Ollama call failed with status code 404.', 'file_name': 'The_Lord_of_the_Rings', 
'status': 'Failed', 'db_url': 'bolt://localhost:7687', 'failed_count': 1, 
'source_type': 'Wikipedia', 'source_url': None, 'wiki_query': 'The_Lord_of_the_Rings', 
'logging_time': '2024-11-15 20:25:37 UTC'}
2024-11-15 15:25:37,192 - File Failed in extraction: {'message': 'Failed To Process File:The_Lord_of_the_Rings or LLM Unable To Parse Content ', 
'error_message': 'Ollama call failed with status code 404.', 'file_name': 'The_Lord_of_the_Rings', 
'status': 'Failed', 'db_url': 'bolt://localhost:7687', 'failed_count': 1, 
'source_type': 'Wikipedia', 'source_url': None, 'wiki_query': 'The_Lord_of_the_Rings', 
'logging_time': '2024-11-15 20:25:37 UTC'}
Traceback (most recent call last):
  File "path_to_code/score.py", line 235, in extract_knowledge_graph_from_file
    uri_latency, result = await extract_graph_from_file_Wikipedia(uri, userName, password, database, model, wiki_query, language, file_name, allowedNodes, allowedRelationship, retry_condition)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_code/src/main.py", line 269, in extract_graph_from_file_Wikipedia
    return await processing_source(uri, userName, password, database, model, file_name,[], allowedNodes, allowedRelationship, retry_condition=retry_condition)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_code/src/main.py", line 370, in processing_source
    node_count,rel_count,latency_processed_chunk = await processing_chunks(selected_chunks,graph,uri, userName, password, database,file_name,model,allowedNodes,allowedRelationship,node_count, rel_count)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_code/src/main.py", line 461, in processing_chunks
    graph_documents =  await get_graph_from_llm(model, chunkId_chunkDoc_list, allowedNodes, allowedRelationship)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_code/src/llm.py", line 207, in get_graph_from_llm
    graph_document_list = await get_graph_document_list(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_code/src/llm.py", line 189, in get_graph_document_list
    graph_document_list = await llm_transformer.aconvert_to_graph_documents(combined_chunk_document_list)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_virtualenv_path/site-packages/langchain_experimental/graph_transformers/llm.py", line 886, in aconvert_to_graph_documents
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_virtualenv_path/site-packages/langchain_experimental/graph_transformers/llm.py", line 819, in aprocess_response
    raw_schema = await self.chain.ainvoke({"input": text}, config=config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_virtualenv_path/site-packages/langchain_core/runnables/base.py", line 3064, in ainvoke
    input = await asyncio.create_task(part(), context=context)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_virtualenv_path/site-packages/langchain_core/language_models/chat_models.py", line 305, in ainvoke
    llm_result = await self.agenerate_prompt(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_virtualenv_path/site-packages/langchain_core/language_models/chat_models.py", line 794, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "path_to_virtualenv_path/site-packages/langchain_core/language_models/chat_models.py", line 754, in agenerate
    raise exceptions[0]
  File "path_to_virtualenv_path/site-packages/langchain_core/language_models/chat_models.py", line 930, in _agenerate_with_cache
    result = await self._agenerate(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_virtualenv_path/site-packages/langchain_community/chat_models/ollama.py", line 323, in _agenerate
    final_chunk = await self._achat_stream_with_aggregation(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_virtualenv_path/site-packages/langchain_community/chat_models/ollama.py", line 244, in _achat_stream_with_aggregation
    async for stream_resp in self._acreate_chat_stream(messages, stop, **kwargs):
  File "path_to_virtualenv_path/site-packages/langchain_community/chat_models/ollama.py", line 203, in _acreate_chat_stream
    async for stream_resp in self._acreate_stream(
  File "path_to_virtualenv_path/site-packages/langchain_community/llms/ollama.py", line 327, in _acreate_stream
    raise OllamaEndpointNotFoundError(
langchain_community.llms.ollama.OllamaEndpointNotFoundError: Ollama call failed with status code 404.
`

Looks like I am getting a 404 error but I am unable to tell how/why I'm getting this error. I believed it was the langchain chatOllama function but was able to test that chatOllama works as intended in a test file.

**Comment by kartikpersistent** [comment]
#730

**Comment by Anesbett1** [comment]
was able to figure it out. 
In my .env file for the backend, I had: 
LLM_MODEL_CONFIG_ollama_llama3 = "llama3,http://localhost:11434/"

changing it to:
LLM_MODEL_CONFIG_ollama_llama3 = "llama3,http://localhost:11434"

I no longer get a 404. Saw it by debugging and seeing the URL it was calling...
