### ISSUE TITLE
Chat mode not working: TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by peterchanws** [neo4j-labs/llm-graph-builder#944]
I installed LLM Graph Builder App and running Backend and Frontend separately (dev environment). I added an article from Wiki: [King Kong (1933 film) - Wikipedia](https://en.wikipedia.org/wiki/King_Kong_(1933_film)).

Got "TypeError: can only concatenate str (not "NoneType") to str" when trying Chat mode. Here is the log in backend:

2024-12-14 15:16:42,439 - QA_RAG called at 2024-12-14 15:16:42.439451
2024-12-14 15:16:42,467 - Checking access for database: neo4j
2024-12-14 15:16:42,475 - Read access count: 0
2024-12-14 15:16:42,475 - The account has write access.
2024-12-14 15:16:42,476 - Chat Mode: graph_vector_fulltext
2024-12-14 15:16:42,768 - Chat mode settings: {'retrieval_query': '\nWITH node as chunk, score\n// find the document of the chunk\nMATCH (chunk)-[:PART_OF]->(d:Document)\n// aggregate chunk-details\nWITH d, collect(DISTINCT {chunk: chunk, score: score}) AS chunks, avg(score) as avg_score\n// fetch entities\nCALL { WITH chunks\nUNWIND chunks as chunkScore\nWITH chunkScore.chunk as chunk\n\n    OPTIONAL MATCH (chunk)-[:HAS_ENTITY]->(e)\n    WITH e, count(*) AS numChunks \n    ORDER BY numChunks DESC \n    LIMIT 40\n\n    WITH \n    CASE \n        WHEN e.embedding IS NULL OR (0.3 <= vector.similarity.cosine($embedding, e.embedding) AND vector.similarity.cosine($embedding, e.embedding) <= 0.9) THEN \n            collect {\n                OPTIONAL MATCH path=(e)(()-[rels:!HAS_ENTITY&!PART_OF]-()){0,1}(:!Chunk&!Document&!__Community__) \n                RETURN path LIMIT 20\n            }\n        WHEN e.embedding IS NOT NULL AND vector.similarity.cosine($embedding, e.embedding) >  0.9 THEN\n            collect {\n                OPTIONAL MATCH path=(e)(()-[rels:!HAS_ENTITY&!PART_OF]-()){0,2}(:!Chunk&!Document&!__Community__) \n                RETURN path LIMIT 40 \n            } \n        ELSE \n            collect { \n                MATCH path=(e) \n                RETURN path \n            }\n    END AS paths, e\n\n    WITH apoc.coll.toSet(apoc.coll.flatten(collect(DISTINCT paths))) AS paths, \n         collect(DISTINCT e) AS entities\n\n    // De-duplicate nodes and relationships across chunks\n    RETURN \n        collect {\n            UNWIND paths AS p \n            UNWIND relationships(p) AS r \n            RETURN DISTINCT r\n        } AS rels,\n        collect {\n            UNWIND paths AS p \n            UNWIND nodes(p) AS n \n            RETURN DISTINCT n\n        } AS nodes, \n        entities\n}\n\n// Generate metadata and text components for chunks, nodes, and relationships\nWITH d, avg_score,\n     [c IN chunks | c.chunk.text] AS texts, \n     [c IN chunks | {id: c.chunk.id, score: c.score}] AS chunkdetails,\n     [n IN nodes | elementId(n)] AS entityIds,\n     [r IN rels | elementId(r)] AS relIds,\n     apoc.coll.sort([\n         n IN nodes | \n         coalesce(apoc.coll.removeAll(labels(n), [\'__Entity__\'])[0], "") + ":" + \n         n.id + \n         (CASE WHEN n.description IS NOT NULL THEN " (" + n.description + ")" ELSE "" END)\n     ]) AS nodeTexts,\n     apoc.coll.sort([\n         r IN rels | \n         coalesce(apoc.coll.removeAll(labels(startNode(r)), [\'__Entity__\'])[0], "") + ":" + \n         startNode(r).id + " " + type(r) + " " + \n         coalesce(apoc.coll.removeAll(labels(endNode(r)), [\'__Entity__\'])[0], "") + ":" + endNode(r).id\n     ]) AS relTexts,\n     entities\n\n// Combine texts into response text\nWITH d, avg_score, chunkdetails, entityIds, relIds,\n     "Text Content:\n" + apoc.text.join(texts, "\n----\n") +\n     "\n----\nEntities:\n" + apoc.text.join(nodeTexts, "\n") +\n     "\n----\nRelationships:\n" + apoc.text.join(relTexts, "\n") AS text, \n     entities\n\nRETURN \n    text, \n    avg_score AS score, \n    {\n        length: size(text), \n        source: COALESCE(CASE WHEN d.url CONTAINS "None" THEN d.fileName ELSE d.url END, d.fileName), \n        chunkdetails: chunkdetails, \n        entities : {\n            entityids: entityIds, \n            relationshipids: relIds\n        }\n    } AS metadata\n', 'top_k': 5, 'index_name': 'vector', 'keyword_index': 'keyword', 'document_filter': False, 'node_label': 'Chunk', 'embedding_node_property': 'embedding', 'text_node_properties': ['text'], 'mode': 'graph_vector_fulltext'}
2024-12-14 15:16:42,769 - Error during chat setup: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "/Users/pchan3/llm-graph-builder/backend/src/QA_integration.py", line 406, in setup_chat
    llm, model_name = get_llm(model=model)
                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/src/llm.py", line 19, in get_llm
    env_key = "LLM_MODEL_CONFIG_" + model
              ~~~~~~~~~~~~~~~~~~~~^~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
2024-12-14 15:16:42,774 - Error processing chat response at 2024-12-14 15:16:42.774582: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "/Users/pchan3/llm-graph-builder/backend/src/QA_integration.py", line 423, in process_chat_response
    llm, doc_retriever, model_version = setup_chat(model, graph, document_names, chat_mode_settings)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/src/QA_integration.py", line 406, in setup_chat
    llm, model_name = get_llm(model=model)
                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/src/llm.py", line 19, in get_llm
    env_key = "LLM_MODEL_CONFIG_" + model
              ~~~~~~~~~~~~~~~~~~~~^~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
2024-12-14 15:16:42,775 - Total Response time is  0.34 seconds
[INFO]{'api_name': 'chat_bot', 'db_url': 'bolt://localhost:7687', 'userName': 'neo4j', 'database': 'neo4j', 'question': 'who is the director', 'document_names': '[]', 'session_id': 'e5976d9a-83b7-4651-a814-dab5aec2330d', 'mode': 'graph_vector_fulltext', 'logging_time': '2024-12-14 23:16:42 UTC', 'elapsed_api_time': '0.34'}
INFO:     127.0.0.1:54270 - "POST /chat_bot HTTP/1.1" 200 OK

**Comment by kaustubh-darekar** [comment]
Hi @peterchanws ,

Can you check configuration in frontend .env file. (Refer [)](https://github.com/neo4j-labs/llm-graph-builder/blob/main/frontend/example.env)

the llm model needs to be defined in following format
VITE_LLM_MODELS="diffbot,openai_gpt_3.5,**openai_gpt_4o**"

and in backend .env
LLM_MODEL_CONFIG_**openai_gpt_4o**="gpt-4o-2024-11-20,openai_api_key"

model format in frontnend & backend should match otherwise it throws TypeError.

**Comment by peterchanws** [comment]
Thanks, for your reply.
I test Chat mode using LLM "Diffbot". I have this in frontend :
VITE_LLM_MODELS="diffbot,openai_gpt_3.5,openai_gpt_4o,ollama_lamma3"; VITE_LLM_MODELS_PROD="diffbot,openai_gpt_3.5,openai_gpt_4o,ollama_lamma3"
and this in backend env:
LLM_MODEL_CONFIG_diffbot="diffbot,diffbot_api_key"
Frontend and backend LLM model format is the same, and still get the "TypeError: can only concatenate str (not "NoneType") to str" error.

**Comment by kaustubh-darekar** [comment]
this seem weird as your configuration is correct.
Can you check what value is getting passed from frontend for model in api payload.
Also add some logs in get_llm function in llm.py to check what model backend is receiving.

**Comment by kaustubh-darekar** [comment]
Check this PR.
#946 

this will probably give better understanding of error you are facing.  If this doesn't solve the issue please share latest logs after this code deployment.
