### ISSUE TITLE
Not able to process txt file uploaded

### ISSUE THREAD

**Issue by peterchanws** [neo4j-labs/llm-graph-builder#977]
I tried to generate a graph for a text file uploaded to the Graph Builder app and got a "Failed" status. Below is part of the log in the backend. I successfully generated a graph for web sources in the same environment.

[ERROR]{'message': 'Failed To Process File:message-20.txt or LLM Unable To Parse Content ', 'error_message': 'Chunks are not created for message-20.txt. Please re-upload file and try again.', 'file_name': 'message-20.txt', 'status': 'Failed', 'db_url': 'bolt://localhost:7687', 'failed_count': 1, 'source_type': 'local file', 'source_url': None, 'wiki_query': None, 'logging_time': '2024-12-27 18:49:35 UTC'}
2024-12-27 10:49:35,223 - File Failed in extraction: {'message': 'Failed To Process File:message-20.txt or LLM Unable To Parse Content ', 'error_message': 'Chunks are not created for message-20.txt. Please re-upload file and try again.', 'file_name': 'message-20.txt', 'status': 'Failed', 'db_url': 'bolt://localhost:7687', 'failed_count': 1, 'source_type': 'local file', 'source_url': None, 'wiki_query': None, 'logging_time': '2024-12-27 18:49:35 UTC'}
Traceback (most recent call last):
  File "/Users/pchan3/llm-graph-builder/backend/score.py", line 209, in extract_knowledge_graph_from_file
    uri_latency, result = await extract_graph_from_file_local_file(uri, userName, password, database, model, merged_file_path, file_name, allowedNodes, allowedRelationship, retry_condition)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/src/main.py", line 232, in extract_graph_from_file_local_file
    return await processing_source(uri, userName, password, database, model, fileName, [], allowedNodes, allowedRelationship, True, merged_file_path, retry_condition)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/src/main.py", line 313, in processing_source
    total_chunks, chunkId_chunkDoc_list = get_chunkId_chunkDoc_list(graph, file_name, pages, retry_condition)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/src/main.py", line 531, in get_chunkId_chunkDoc_list
    raise Exception(f"Chunks are not created for {file_name}. Please re-upload file and try again.")
Exception: Chunks are not created for message-20.txt. Please re-upload file and try again.

**Comment by peterchanws** [comment]
I tried another file book.txt. Somehow, the system delete the file "2024-12-27 19:16:31,758 - file book.txt deleted successfully"

2024-12-27 19:16:31,694 - File path:/Users/pchan3/llm-graph-builder/backend/merged_files/book.txt
2024-12-27 19:16:31,695 - Process file name :book.txt
2024-12-27 19:16:31,695 - file book.txt processing
2024-12-27 19:16:31,758 - Deleted File Path: /Users/pchan3/llm-graph-builder/backend/merged_files/book.txt and Deleted File Name : book.txt
2024-12-27 19:16:31,758 - file book.txt deleted successfully
[ERROR]{'message': 'Failed To Process File:book.txt or LLM Unable To Parse Content ', 'error_message': 'Error while reading the file content or metadata', 'file_name': 'book.txt', 'status': 'Failed', 'db_url': 'bolt://localhost:7687', 'failed_count': 1, 'source_type': 'local file', 'source_url': None, 'wiki_query': None, 'logging_time': '2024-12-28 03:16:31 UTC'}
2024-12-27 19:16:31,758 - File Failed in extraction: {'message': 'Failed To Process File:book.txt or LLM Unable To Parse Content ', 'error_message': 'Error while reading the file content or metadata', 'file_name': 'book.txt', 'status': 'Failed', 'db_url': 'bolt://localhost:7687', 'failed_count': 1, 'source_type': 'local file', 'source_url': None, 'wiki_query': None, 'logging_time': '2024-12-28 03:16:31 UTC'}
Traceback (most recent call last):
  File "/Users/pchan3/llm-graph-builder/backend/src/document_sources/local_file.py", line 38, in get_documents_from_file_by_path
    unstructured_pages = loader.load()
                      ^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.12/site-packages/langchain_core/document_loaders/base.py", line 31, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.12/site-packages/langchain_community/document_loaders/unstructured.py", line 107, in lazy_load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.12/site-packages/langchain_community/document_loaders/unstructured.py", line 228, in _get_elements
    return partition(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.12/site-packages/unstructured/partition/auto.py", line 181, in partition
    file_type = detect_filetype(
                ^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.12/site-packages/unstructured/file_utils/filetype.py", line 98, in detect_filetype
    return _FileTypeDetector.file_type(ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.12/site-packages/unstructured/file_utils/filetype.py", line 131, in file_type
    return cls(ctx)._file_type
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.12/site-packages/unstructured/file_utils/filetype.py", line 141, in _file_type
    if file_type := self._file_type_from_guessed_mime_type:
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.12/site-packages/unstructured/file_utils/filetype.py", line 181, in _file_type_from_guessed_mime_type
    mime_type = self._ctx.mime_type
                ^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.12/site-packages/unstructured/utils.py", line 154, in __get__
    value = self._fget(obj)
            ^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.12/site-packages/unstructured/file_utils/filetype.py", line 362, in mime_type
    import magic
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.12/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
               ^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.12/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pchan3/llm-graph-builder/backend/score.py", line 209, in extract_knowledge_graph_from_file
    uri_latency, result = await extract_graph_from_file_local_file(uri, userName, password, database, model, merged_file_path, file_name, allowedNodes, allowedRelationship, retry_condition)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/src/main.py", line 227, in extract_graph_from_file_local_file
    file_name, pages, file_extension = get_documents_from_file_by_path(merged_file_path,fileName)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/src/document_sources/local_file.py", line 41, in get_documents_from_file_by_path
    raise Exception('Error while reading the file content or metadata')
Exception: Error while reading the file content or metadata
INFO:     127.0.0.1:61343 - "POST /extract HTTP/1.1" 200 OK
INFO:     127.0.0.1:61347 - "GET /update_extract_status/book.txt?url=bolt://localhost:7687&userName=neo4j&password=cGFzc3dvcmQ=&database=neo4j HTTP/1.1" 200 OK
2024-12-27 19:16:31,933 -  SSE Client disconnected
2024-12-27 19:16:31,934 - update KNN graph

**Comment by NAMEs** [comment]
Same mistake. Did you fix it?

**Comment by peterchanws** [comment]
I am waiting for the neo4j grapher builder team to response.

**Comment by smartwhale8** [comment]
Hi @peterchanws, not from neo4j, but few things from the logs which caught my attention:
1. `'error_message': 'Error while reading the file content or metadata'`: This seems to the root of the failure.
2. `ImportError: failed to find libmagic. Check your installation`:   Try installing this module "pip install python-libmagic". Libmagic is the module used to identify file types. This step is failing as the module is missing.

_Additionally_:
`&userName=neo4j&password=`: Please take care to remove your passwords when posting logs.

**Comment by peterchanws** [comment]
Thanks, smartwhale8. I installed python-libmagic. Still failed to generate graph. 

I am wondering when the txt file was deleted:

2024-12-31 08:24:08,745 - File path:/Users/pchan3/llm-graph-builder/backend/merged_files/message-2351.txt
2024-12-31 08:24:08,745 - Process file name :message-2351.txt
2024-12-31 08:24:08,745 - file message-2351.txt processing
2024-12-31 08:24:09,711 - Deleted File Path: /Users/pchan3/llm-graph-builder/backend/merged_files/message-2351.txt and Deleted File Name : message-2351.txt
2024-12-31 08:24:09,712 - file message-2351.txt deleted successfully
[ERROR]{'message': 'Failed To Process File:message-2351.txt or LLM Unable To Parse Content ', 'error_message': 'Error while reading the file content or metadata', 'file_name': 'message-2351.txt', 'status': 'Failed', 'db_url': 'bolt://localhost:7687', 'failed_count': 1, 'source_type': 'local file', 'source_url': None, 'wiki_query': None, 'logging_time': '2024-12-31 16:24:09 UTC'}
2024-12-31 08:24:09,712 - File Failed in extraction: {'message': 'Failed To Process File:message-2351.txt or LLM Unable To Parse Content ', 'error_message': 'Error while reading the file content or metadata', 'file_name': 'message-2351.txt', 'status': 'Failed', 'db_url': 'bolt://localhost:7687', 'failed_count': 1, 'source_type': 'local file', 'source_url': None, 'wiki_query': None, 'logging_time': '2024-12-31 16:24:09 UTC'}

**Comment by kartikpersistent** [comment]
Hi @peterchanws what is GCS_FILE_CACHE value in env

**Comment by peterchanws** [comment]
I have GCS_FILE_CACHE = "" initially.
I changed that to GCS_FILE_CACHE = False and also True and still got "Failed".

**Comment by kartikpersistent** [comment]
Try with GCS_FILE_CACHE as False and check whether the files are saving in the backend folder

**Comment by peterchanws** [comment]
In which folder under the \backend directory should I look for the file?

**Comment by kartikpersistent** [comment]
In chunks folder you will get chunks

**Comment by peterchanws** [comment]
I added the file "message-2.txt" and it appears under merged_files folder. After I click "Generate Graph", it disappear from the merged_files folder.

**Comment by peterchanws** [comment]
Nothing in the chunks folder

**Comment by kartikpersistent** [comment]
so extraction failed again?

**Comment by peterchanws** [comment]
yes

**Comment by kartikpersistent** [comment]
![{A0F50CCE-5E89-4182-B6FC-8CE34EEE857F}](https://github.com/user-attachments/assets/01868070-3b28-4b6a-96bb-5a3cce6ae626)
it is working at our end 
![{66209702-54E1-4C61-A6A4-055F2148AD73}](https://github.com/user-attachments/assets/6e971e24-2471-45e4-b67f-83582c2ac287)

**Comment by peterchanws** [comment]
mineis:
OPENAI_API_KEY = ""
#EMBEDDING_MODEL can be openai or vertexai or by default all-MiniLM-L6-v2
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
# RAGAS_EMBEDDING_MODEL = "openai"
RAGAS_EMBEDDING_MODEL = "ollama"
IS_EMBEDDING = "true"
KNN_MIN_SCORE = "0.94"
# Enable Gemini (default is False) | Can be False or True
GEMINI_ENABLED = False
# Enable Google Cloud logs (default is False) | Can be False or True
GCP_LOG_METRICS_ENABLED = False
NUMBER_OF_CHUNKS_TO_COMBINE = 6
UPDATE_GRAPH_CHUNKS_PROCESSED = 20
NEO4J_URI = "bolt://localhost:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "xxxxx"
NEO4J_DATABASE = "neo4j"
AWS_ACCESS_KEY_ID =  ""
AWS_SECRET_ACCESS_KEY = ""
LANGCHAIN_API_KEY = ""
LANGCHAIN_PROJECT = ""
LANGCHAIN_TRACING_V2 = True
LANGCHAIN_ENDPOINT = "https://api.smith.langchain.com"
GCS_FILE_CACHE = False
NEO4J_USER_AGENT=""
ENABLE_USER_AGENT = ""
LLM_MODEL_CONFIG_model_version=""
ENTITY_EMBEDDING= False
DUPLICATE_SCORE_VALUE =0.97
DUPLICATE_TEXT_DISTANCE =3
# DEFAULT_DIFFBOT_CHAT_MODEL="openai_gpt_4o"  #whichever model specified here , need to add config for that model in below format)
DEFAULT_DIFFBOT_CHAT_MODEL="ollama"
#examples
LLM_MODEL_CONFIG_openai_gpt_3.5="gpt-3.5-turbo-0125,openai_api_key"
LLM_MODEL_CONFIG_openai_gpt_4o_mini="gpt-4o-mini-2024-07-18,openai_api_key"
LLM_MODEL_CONFIG_openai_gpt_4o="gpt-4o-2024-11-20,openai_api_key"
LLM_MODEL_CONFIG_gemini_1.5_pro="gemini-1.5-pro-002,gemini_api_key"
LLM_MODEL_CONFIG_gemini_1.5_flash="gemini-1.5-flash,gemini_api_key"
LLM_MODEL_CONFIG_diffbot="diffbot,diffbot_api_key"
LLM_MODEL_CONFIG_azure_ai_gpt_35="azure_deployment_name,azure_endpoint or base_url,azure_api_key,api_version"
LLM_MODEL_CONFIG_azure_ai_gpt_4o="gpt-4o,https://YOUR-ENDPOINT.openai.azure.com/,azure_api_key,api_version"
LLM_MODEL_CONFIG_groq_llama3_70b="model_name,base_url,groq_api_key"
LLM_MODEL_CONFIG_anthropic_claude_3_5_sonnet="Claude-3.5-Sonnet-2024-10-22,Claude_api_key"
LLM_MODEL_CONFIG_fireworks_llama_v3_70b="model_name,fireworks_api_key"
LLM_MODEL_CONFIG_bedrock_claude_3_5_sonnet="model_name,aws_access_key_id,aws_secret__access_key,region_name"

**Comment by peterchanws** [comment]
You have "BUCKET = "....." in your .env file. I don't have this.

**Comment by peterchanws** [comment]
I don't have NPM_TOKEN = "...." as well.
Do you have local deployment? Neo4j Desktop,

**Comment by kartikpersistent** [comment]
that is for testing gcs uploads but locally we are setting GCS_FILE_CACHE="False" so that files will get stored in local memory and NPM_TOKEN is not required now as neo4j ndl is public now

**Comment by kartikpersistent** [comment]
apt-get update && \
   apt-get install -y --no-install-recommends \
       libmagic1 \
       libgl1-mesa-glx \
       libreoffice \
       cmake \
       poppler-utils \
       tesseract-ocr && \
   apt-get clean && \
   rm -rf /var/lib/apt/lists/*
   
   run these commands in your machine these are system dependencies for unstructure loader

**Comment by peterchanws** [comment]
I am using macOS. The commands you provided don't work. Could you please give me the commands for macOS?

**Comment by peterchanws** [comment]
I ask Chatgpt for the macOS equivalent for your commands and got:
brew update && \
brew install libmagic open-mpi libreoffice cmake poppler tesseract && \
brew cleanup

Is that correct?

**Comment by kartikpersistent** [comment]
yes you can use brew

**Comment by peterchanws** [comment]
I got this after brew cleanup:
==> Updating Homebrew...
Already up-to-date.
Warning: Treating cmake as a formula. For the cask, use homebrew/cask/cmake or specify the `--cask` flag. To silence this message, use the `--formula` flag.
Warning: Not upgrading libreoffice, the latest version is already installed
Warning: libmagic 5.46 is already installed and up-to-date.
To reinstall 5.46, run:
  brew reinstall libmagic
Warning: open-mpi 5.0.6 is already installed and up-to-date.
To reinstall 5.0.6, run:
  brew reinstall open-mpi
Warning: cmake 3.31.3 is already installed and up-to-date.
To reinstall 3.31.3, run:
  brew reinstall cmake
Warning: poppler 24.12.0 is already installed and up-to-date.
To reinstall 24.12.0, run:
  brew reinstall poppler
Warning: tesseract 5.5.0 is already installed and up-to-date.
To reinstall 5.5.0, run:
  brew reinstall tesseract
(base) (envName) pchan3@li-ar-4126 backend % rm -rf /var/lib/apt/lists/*
zsh: sure you want to delete all the files in /var/lib/apt/lists [yn]? y
zsh: no matches found: /var/lib/apt/lists/*

After that I restart the backend. Unfortunately, I still got "Failed" status trying to process uploaded file.

**Comment by kartikpersistent** [comment]
ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

Set the library path

**Comment by peterchanws** [comment]
I use this as the equivalent for your command for mac (suggested by ChatGPT): export DYLD_LIBRARY_PATH=/usr/lib:$DYLD_LIBRARY_PATH


When I use "uvicorn score:app --reload" again, I got the following and not able to start the backend.


Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.11/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/pchan3/llm-graph-builder/backend/score.py", line 4, in <module>
    from src.main import *
  File "/Users/pchan3/llm-graph-builder/backend/src/main.py", line 15, in <module>
    from src.graphDB_dataAccess import graphDBdataAccess
  File "/Users/pchan3/llm-graph-builder/backend/src/graphDB_dataAccess.py", line 5, in <module>
    from src.document_sources.gcs_bucket import delete_file_from_gcs
  File "/Users/pchan3/llm-graph-builder/backend/src/document_sources/gcs_bucket.py", line 11, in <module>
    import nltk
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.11/site-packages/nltk/__init__.py", line 153, in <module>
    from nltk.translate import *
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.11/site-packages/nltk/translate/__init__.py", line 24, in <module>
    from nltk.translate.meteor_score import meteor_score as meteor
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.11/site-packages/nltk/translate/meteor_score.py", line 13, in <module>
    from nltk.corpus import WordNetCorpusReader, wordnet
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.11/site-packages/nltk/corpus/__init__.py", line 64, in <module>
    from nltk.corpus.reader import *
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.11/site-packages/nltk/corpus/reader/__init__.py", line 106, in <module>
    from nltk.corpus.reader.panlex_lite import *
  File "/Users/pchan3/llm-graph-builder/backend/envName/lib/python3.11/site-packages/nltk/corpus/reader/panlex_lite.py", line 15, in <module>
    import sqlite3
  File "/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: dlopen(/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/lib-dynload/_sqlite3.cpython-311-darwin.so, 0x0002): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: <DA6BD5A4-F242-30D5-AC7F-161817EEE8C3> /opt/homebrew/Caskroom/miniconda/base/lib/python3.11/lib-dynload/_sqlite3.cpython-311-darwin.so
  Expected in:     <3791084A-969D-36E3-B3AD-AC9CB500EC27> /usr/lib/libsqlite3.dylib

**Comment by peterchanws** [comment]
I switched to Python 3.11, and the error vanished. The status is now “Completed.” I truly appreciate your patience in assisting me despite my lack of technical expertise.

**Comment by kartikpersistent** [comment]
Yes there is some problem with the Python 3.12 version with other associated libraries we will mention that In Readme thanks for trying out our application

**Comment by kartikpersistent** [comment]
If things are working  close the issue

**Comment by peterchanws** [comment]
Thanks again.
